// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLVVQarC01Cm1KFESqRRsMFuBMbr9XNe8',
    appId: '1:376417530582:web:074d2b27cd88899480cf77',
    messagingSenderId: '376417530582',
    projectId: 'fir-gns',
    authDomain: 'fir-gns.firebaseapp.com',
    storageBucket: 'fir-gns.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh0sw-9F_kTi5jTrC8T3_YFLrHROdMpxY',
    appId: '1:376417530582:android:7d09ccdda775074680cf77',
    messagingSenderId: '376417530582',
    projectId: 'fir-gns',
    storageBucket: 'fir-gns.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv3Ug_uaQzgXx3UpSBHGwJQ7CEDr5PI3c',
    appId: '1:376417530582:ios:d4c59fe1947a012780cf77',
    messagingSenderId: '376417530582',
    projectId: 'fir-gns',
    storageBucket: 'fir-gns.appspot.com',
    iosClientId:
        '376417530582-kdk70i7k4obc4unon1dq1ks64477fovt.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourProjectName',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv3Ug_uaQzgXx3UpSBHGwJQ7CEDr5PI3c',
    appId: '1:376417530582:ios:1a0aecd32313677780cf77',
    messagingSenderId: '376417530582',
    projectId: 'fir-gns',
    storageBucket: 'fir-gns.appspot.com',
    iosClientId:
        '376417530582-usr25mo3tb2kq944mg4hs7fkm5fb0ouj.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourProjectName.RunnerTests',
  );
}
